### ISSUE TITLE
Preparar o ambiente de rotas no Frontend

### ISSUE THREAD

**Issue by allbertuu** [SouJunior/linkedin-frontend#15]

**Comment by SilviaLTeixeira** [comment]
O ambiente de rotas em si esta preparado mas cancelei o meu PR por motivos de conflito entre as alteraçoes do @allbertuu e as minhas . Nao estou conseguindo mergear nem fazer nada que junte as duas branch por esse motivo vou deixar no block ate alguem conseguir me ajudar com esta questao 
@wouerner
