### ISSUE TITLE
Crud - Vagas simples

### ISSUE THREAD

**Issue by wouerner** [SouJunior/linkedin-frontend#2]
O usuário gostaria de entrar no sistema deslogado e cadastrar vagas, visualizar, editar e apagar essa vaga, com os dados:

- Titulo da vaga
- descrição
- Tipo: Estagio, Trainee ou Junior

OBS: o login será feito em outra tarefa.

**Comment by allbertuu** [comment]
## Justificativa adiamento do prazo (25/07)
Devido a eu estar ocupado essa semana com outras responsabilidades, e perceber em conversa com a equipe que ainda faltam algumas coisas para serem aprendidas até efetivamente essa task ser iniciada, combinei com o Wouerner e a Larissa sobre o adiamento da deadline de sexta (22/07) para segunda (25/07).
