### ISSUE TITLE
[COMPONENTE] Input

### ISSUE THREAD

**Issue by CaaioSB** [SouJunior/linkedin-frontend#29]
### Sua solicitação de recurso está relacionada a um problema?
Não necessariamente a um problema, mas para otimizar o desenvolvimento das interfaces é interessante começar pela criação dos componentes que serão reutilizados, portanto o ideal nesse momento é parar o desenvolvimento das interfaces e dar prioridade aos componentes.

### Descreva a solução que você deseja
Essa issue é exclusivamente para a criação do componente Input, vide [Figma](https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX?node-id=246%3A1764).

![image](https://user-images.githubusercontent.com/34246280/186781063-e7fcb5c4-f792-4979-b558-537587d5f157.png)

### Descrição detalhada
O Input é um dos componentes mais importantes, precisa ser desenvolvido visando as variantes, são elas:

<details>
<summary>Clique aqui para abrir mais detalhes sobre os componentes, esses detalhes não estão formalizados no 
 componente Input do Figma, portanto precisa garimpar para achar as possíveis variantes.</summary>
<br />

Contained com ícone
![image](https://user-images.githubusercontent.com/34246280/186781573-338922e2-ff5a-4a25-bca9-b57da7cfb45c.png)

Contained sem ícone
![image](https://user-images.githubusercontent.com/34246280/186781673-af141e15-0db1-4101-89ca-6f50256078b1.png)

Contained small com foco
![image](https://user-images.githubusercontent.com/34246280/186781781-68d3255f-7ec1-43cf-bdce-fda45c5e174c.png)

Contained Small (com outro background color)
![image](https://user-images.githubusercontent.com/34246280/186781413-fb7b5aa1-c784-4970-820e-e6c65ec23094.png)

Multiplas linhas
![image](https://user-images.githubusercontent.com/34246280/186782194-194a8586-dbd4-4ccb-8376-a7a892b536c0.png)

</details>

Até então variações é o suficiente para continuar com o desenvolvimento das primeiras interfaces.

**Comment by wouerner** [comment]
@nesantana Por favor, validar a necessidade da criação de componentes.

Até o @nesantana validar, a issue vai ficar aberta como sugestão de melhoria, caso a issue não seja valida vamos fechar novamente.
