### ISSUE TITLE
Screen: Report Screen

### ISSUE THREAD

**Issue by wouerner** [SouJunior/linkedin-frontend#9]
Prototipo: https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX?node-id=145%3A302

**Comment by Rhyan-eduardo** [comment]
![Image](https://user-images.githubusercontent.com/67023605/184435155-2ae8bf7a-bcae-4b23-ba23-597b1417adb7.png)

Link do Protótipo da Tela de Login no Figma : 
[Tela de Denúncias ](https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX?node-id=246%3A1077)

**Comment by Rhyan-eduardo** [comment]
Os ativos estão sendo preparados para exportação!

Todos os ativos de suas respectivas telas estão neste proprietário no drive : 
[Google Drive](https://drive.google.com/drive/folders/1-DmGt1gOwJn4qFsYaGJEa3Flw-4W0z8e?usp=sharing)

( Comunicar a @Rhyan-eduardo  falta de possível ativo... )

**Comment by ArthurMaciel95** [comment]
Olá 👋 
Não sou parte da equipe mas gostaria de finalizar essa issues! Tenho sinal verde pra prosseguir?

**Comment by Rhyan-eduardo** [comment]
SIM

**Comment by Rhyan-eduardo** [comment]
> Olá👋 Não sou parte da equipe, mas gostaria de finalizar essas questões! Tenho sinal verde prático?

SIM

**Comment by allbertuu** [comment]
Esperando revisão (approve) dos mentores.
